import {normalizeCode,lookupId,seal} from './card-crypto.mjs';
const $=id=>document.getElementById(id);let manifest=null;
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error('Could not load the current website data. Refresh and try again.');return r.json();}
Promise.all([json('data/hosts.json'),json('data/cards.json')]).then(([h,d])=>{if(!h.hosts.length||!d.cards.length){$('message').textContent='Pilot setup is pending. Host profiles and invitation batches must be loaded before contact setup and activation.';}for(const host of h.hosts){const option=document.createElement('option');option.value=host.id;option.textContent=host.firstName;$('host').append(option);const c=d.cards.filter(c=>c.hostId===host.id);const row=document.createElement('tr');for(const value of [host.firstName,c.filter(c=>c.status==='inactive').length,c.filter(c=>['active','handed_out'].includes(c.status)).length,c.filter(c=>c.status==='requested').length,c.filter(c=>c.status==='scheduled').length,c.filter(c=>c.status==='completed').length]){const td=document.createElement('td');td.textContent=value;row.append(td);}$('summary').append(row);}}).catch(e=>$('message').textContent=e.message);
$('manifest').onchange=async()=>{try{const f=$('manifest').files[0];if(!f||f.size>250000)throw Error('Choose the supplied private pilot manifest.');const m=JSON.parse(await f.text());if(m.version!==1||!Array.isArray(m.cards)||m.cards.length!==80)throw Error('Choose the supplied 80-card pilot manifest.');manifest=m;$('message').textContent='Private manifest loaded in this browser only.';}catch(e){manifest=null;$('message').textContent=e.message;}};
$('encrypt').onclick=async()=>{const button=$('encrypt');button.disabled=true;try{if(!manifest)throw Error('Load the private manifest first.');const hostId=$('host').value;let phone=$('phone').value.replace(/\D/g,'');if(!/^1?\d{10}$/.test(phone))throw Error('Enter a US phone number including the area code.');if(phone.length===10)phone='1'+phone;
  const current=await json('data/cards.json');const secrets=manifest.cards.filter(c=>c.hostId===hostId);if(secrets.length!==10)throw Error('This host bundle does not match the pilot.');
  for(const s of secrets){const c=current.cards.find(c=>c.ref===s.ref&&c.hostId===hostId);const code=normalizeCode(s.code);if(!c||await lookupId(code)!==c.locks.code.id||await lookupId(s.token)!==c.locks.qr.id)throw Error('The private manifest does not match the current cards.');const payload={hostId,ref:c.ref,phone};c.locks={code:await seal(code,payload),qr:await seal(s.token,payload)};c.contactReady=true;c.updatedAt=new Date().toISOString();}
  current.updatedAt=new Date().toISOString();const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)+'\n'],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cards.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);$('phone').value='';$('message').textContent='Encrypted update downloaded. Upload cards.json into the GitHub data folder now. No live changes have been made yet.';
}catch(e){$('message').textContent=e.message;}finally{button.disabled=false;}};
